server:
  port: 8130 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tS89cyQMN1wfVZMBxQo
    keySecret: h2yXPRxz7Tu5uf7PJmNo6fw7T9k0RT
    bucketName: srb-file-20000401